language: scala

scala:
  - "2.12.5"

jdk:
  - oraclejdk8

jobs:
  include:
    - stage: test
      script: sbt test

    - stage: deploy
      script: sbt publish
      if: repo = 2m/sssio

    - stage: sync maven central
      script: sbt bintraySyncMavenCentral
      if: repo = 2m/sssio AND tag =~ ^v

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

env:
  global:
    # travis encrypt BINTRAY_USER=...
    - secure: "Q7+nUF16iWVX35z8XDC5L4x+AtTJGIN98tJe+Ef1DqFWjKwmWOzFWrST2mxokmpDW75OnFNqLmAG40bPTY+2p/Q9SA6Qz395JXVum5Hl7uW/PvrXoBcvAS6kP4ayVBN7aLJLgjIZ92PBpV8KSJR0Bt7YzYCHAntt565/BRvL1ELy3NoJ56IkvZujJcHOUju4gHrADdFt7sNkGevl9ihCFSdXo83FPrRjRFMPZnFvyGTtaPeRkx4OHkgMvToiV+p3OC8/q9APnyLfQqwAplXmZV7EstnCH/AsazQGjFwYjccqdeUh8OIp0FFxyQ/3VBL7nvFrVAgkNzjJiaQvIDvkP1jXOncoTJJNmohcpO/CIqAlDWQf6tZ9SieGsguqpp4GOPRuVXnG+WlTMra98DJj2C/xv3jMNQFRFkPkJ48Slgr/yQHwn5q3iidbAJ7Kab2Nwhna5KVRjfe8lt73RkzLBzy5BSvsVweK+DoGYXOyIZC5Wh8rykLUaAR8GHaxqSZVwLh71BtLhFMJvKW2m41iRbeWkj1S2ZQ0pyfC11wL6HCe6dl81yaIcBwFrtTGdSh8eHusNE2TC/aL4MustDaF/SpxC7OCLXPE3haK5LNya1wHglDFNY/p12/l5FvOTjIen2DLAiGoc7kyZKbTAEhNLPjdgcN6ZGrQfW9/wv5dHAg="
    # travis encrypt BINTRAY_PASS=...
    - secure: "kC9jAuOW75xlC59Vbqjpoic6V6Qmi2noMW09lZexhjm6FTbSVzM8ikd1zaqnRXOFrCW4pwdgZFgypLzTII0Oj7tqb7WkkzZU35w3prCn/lvBWfZryOoIlfdO+txH2tHO8K4MlvjVL2cK2rEmX9jJzlUGvTBCLxZKLJRRVhRlow5CZ1ijoHnplS+1kROexO5oJgE3gXY3zbMZ3ijEeGnRimcuvzcMZlVOrKkmdOHAPy5/tV62Id03yd1WjoPAxynPCqx6+8ZOSF0U1b+1AFv7ncXIyDqdmTEDjpwiAvs0T8cAKQpPO3YIL+Bv3h+i26g+s1yzAyNNkhAKgYLnZNlBGnM60iv/ZC/XTRrfPHSo5utWalqh5rH4cae+dK7eGzU2tv8iHgORegZK2XCXFmbJv7XKCG1lMd4zSwJdYAxjOiMUWdHvryM+frS9Ydyzvzq4IdpYK22W4b1YsifgGyKnt+qkPui7tX4SeK1OG9WkKNJJCEgv3JtcVeEtHvhmqqmJD5R4JERdeZXnaSz1ZF89DDo1ndqNN9VUdeQKEGnkjRW21VTVThqGP2U8hwlO+elTNrPbkNeIG9qcY3nR5QXumSZLZmS7uRm6JBRzlAgXaVeRAm2rgjMTeKnOFTiIiKolR4HrdgipJbjcyC0srL3FU7FQJr4gn4kGBRZe1hE+ygw="
    # travis encrypt SONA_USER=...
    - secure: "RxlAD/a0TeoUky68f1Hc4/OonG7lzsuCMcWmvzjYREta1DOZkI9R/8igJjdDMc8FoyvShEZOux1nG6DWWalgFz++6wdcPNr/uwMnbPsy73zrI11fxpk7bEaXJY+sbcWq955jOUwuPd4Ech2uGchMTNKNANrMl6iXi3OPWqrbB6yreuSTtZn08i14Q5yNJ+mx3qMIbn5M+Mg/7NQwbJ3Ku5z2xetfQymCAQNfgLeF00nztQxj4UDGPJPwWzPJBgwfSChp6NN8bWM9EARMsaMafD7bS1uOf8HQnKIm4yPn/qtYGP/IYmDLfmFSpGrncOcdmysshpH3Ab6y3ThVXol5SZ8qyzffQDajMX7MtFVDlOsqYn4dY7rnEAIBhI6ystOBZGSd4b/kLIl3KXNItYjPxOM0E2WxZiFpXXEWjvCV1fSWjcI64IMgxP3imFO5i/dmrN91GtRqhJTSeX1NHxAV2+zFmIMmessDp+ETuhwiLggq1h1VPoVmN0dyT5ND27XX6eLpDLkjU+SWSzzESpXJWae80f8y0pqCMM5sXp6hZxHAkvuyfrqbZNUckQifdZEWOcaQyFQUBTnSPVSnC9B6qtHI4u2pbiL8Vr/jqZbZDBpnXt98O0R8vdAmNwOX5pKd3ZqbqGiPj/1ZgEgAkBYQV1DzNWBBeJqaGUBOJRuglkk="
    # travis encrypt SONA_PASS=...
    - secure: "XZlsb5V0g9GqJd9sHWNK2u51Ob+hI51qLII3jSN+o7mffFZ2387Rrz2q2zv+1dWU7CyU16GF8e66cPZrgJqOrvENTMs2ll/DmEoCafKit00xmEyHx28maHnkECsBL/8HMSOaMGzCJ9UbGlGm9iOnOBKoHvL8IDd3OoQW2+Y2DgjpHDqbNMlP9ae+NiULC8Yn/Ubfh5oYoeFkYegDlybAqclqoeVcEIxs4AwwfMwFoZRwSQ7cx2j0qXl9aQDyKQFNmojaHGGQ/mntL13xdhowbC7w6gXEoYr5mucyiSDkLqynog2mzvVz3w5lzuen7KQtif5yNA0W/AeVCUuDMCSNuJFkjmJ4Ng8eWstXjOP8VS1HZuW42A2P5RKbUecgTWLKjsoMOb5I9SVM7PkyyhmZOnn1iVkCWWROq3VKNhjPUC9jlJ13JlF/0tLuhVyYl1z4PvflrqzFgllN3sVGT29qzEMClttIiV5iXS/ZkaP34mHZva08213TAh6rEsZP567Xn+/smZtrYDTI+3FKeiQV3/JRQa+rztYwsVQEztGM6dvoM6JZ+WpW7IPYfC8C1DyGzCj7YISP/OXC+am+WeaMPj+afjo00OUqsx8mCSGOK5Oy18BFkqagbO+qm+5Squp0IgJx5ngp89oGZkQEnn3AgiqF5Nrmj2DKcIdlFcSnXV0="
